apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-tomcat
  namespace: default
spec:
  replicas: 3
  selector:
     matchLabels:
        app: myapp
        diskType: ssd
  template:
     metadata:
       namespace: default
       labels:
         app: myapp
         release: tomcat
         diskType: ssd
     spec:
       containers:
       - name: tomcat
         image: tomcat
         imagePullPolicy: IfNotPresent
         ports:
         - name: tomcat
           containerPort: 8080
                
