---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html
  namespace: default
  labels:
    release: linux
spec:
  accessModes:
  - ReadWriteMany
  selector:
    matchLabels: 
      release: linux
  resources:
    requests:
     storage: 1.5G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx
  namespace: default
  labels:
    release: linux
spec:
  accessModes:
  - ReadWriteMany
  selector:
    matchLabels: 
      release: linux
  resources:
    requests:
     storage: 2G
