---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  labels:
   release: linux
spec:
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /mnt/pv001
    type: DirectoryOrCreate 
  capacity:
    storage: 2G
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002
  labels:
   release: linux
spec:
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /mnt/pv002
    type: DirectoryOrCreate
  capacity:
    storage: 1G
