---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sts-1
  namespace: default
  labels:
    release: linux
spec:
  accessModes:
  - ReadWriteMany
  selector:
    matchLabels: 
      release: linux
  resources:
    requests:
     storage: 5G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sts-2
  namespace: default
  labels:
    release: linux
spec:
  accessModes:
  - ReadWriteMany
  selector:
    matchLabels: 
      release: linux
  resources:
    requests:
     storage: 5G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sts-3
  namespace: default
  labels:
    release: linux
spec:
  accessModes:
  - ReadWriteMany
  selector:
    matchLabels: 
      release: linux
  resources:
    requests:
     storage: 10G
